version: "3"

includes:
  api-golang:
    taskfile: ./apps/api-golang/Taskfile.yaml
    dir: ./apps/api-golang
  api-node:
    taskfile: ./apps/api-node/Taskfile.yaml
    dir: ./apps/api-node
  client-react:
    taskfile: ./apps/client-react/Taskfile.yaml
    dir: ./apps/client-react
  load-generator-python:
    taskfile: ./apps/load-generator-python/Taskfile.yaml
    dir: ./apps/load-generator-python
  migrations:
    taskfile: ./migrations/Taskfile.yaml
    dir: ./migrations

vars:
  DATABASE_URL: "postgres://postgres:password@localhost:6543/postgres"

tasks:
  bootstrap-buildx-builder:
    desc: Bootstrap the builder
    cmds:
      - docker buildx create --name mybuilder --driver docker-container --driver-opt network=host --use
      - docker buildx inspect mybuilder --bootstrap
      - docker buildx use mybuilder

  run-local-registry:
    desc: Run a local registry
    cmds:
      - docker run -d -p 5000:5000 registry:2.8
      
  tilt-up:
    desc: "Start the applications using the top level tilt file"
    cmds:
      - tilt up
