version: "3"

vars:
  DATABASE_URL: "postgres://postgres:password@localhost:6543/postgres"
  IMAGE_REPO: astritdemiri11/kubernetes-fullstack-api-app
  IMAGE_TAG: api-golang

tasks:
  install:
    desc: "download dependencies"
    cmds:
      - go mod tidy

  run:
    desc: "download dependencies"
    cmds:
      - echo $PWD
      - ls
      - DATABASE_URL={{.DATABASE_URL}} go run main.go

  build-container-image:
    desc: Build container image
    cmds:
      - |
        KO_DOCKER_REPO='{{.IMAGE_REPO}}' \
          ko build \
          --bare \
          --tags={{.IMAGE_TAG}} \
          --platform=all

  build-container-image-multi-arch:
    cmds:
      - task: build-container-image
