apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: kubernetes-fullstack-api-app
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/astritdemiri11/kubernetes-fullstack-api-app/db-migrations:v1.0.0
          args:
            - -path=/app/migrations
            - -database=$(DATABASE_URL)?sslmode=disable
            - up
          envFrom:
            - secretRef:
                name: db-connection
      restartPolicy: OnFailure
