# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: kubernetes-fullstack-api-app
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:password@cnpg-kubernetes-fullstack-api-app-rw.kubernetes-fullstack-api-app.svc.cluster.local:5432/postgres
