version: '3'

vars:
  IMAGE_REPO: ghcr.io/astritdemiri11/kubernetes-fullstack-api-app/db-migrations
  IMAGE_TAG: v1.0.0

tasks:
  apply-initial-db-migration-job:
    desc: "Run init.sql script against the DB"
    cmds:
      - "kubectl apply -f Secret.yaml"
      - "kubectl apply -f Job.yaml"
