apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-daily-backup-kubernetes-fullstack-api-app
  namespace: kubernetes-fullstack-api-app
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-kubernetes-fullstack-api-app
