version: '3'

vars:
  DATABASE_URL: 'postgres://postgres:password@localhost:6543/postgres'
  IMAGE_REPO: ghcr.io/astritdemiri11/kubernetes-fullstack-api-app/api-node
  IMAGE_TAG: v1.0.0

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: install dependencies
    cmds:
      - npm install

  run:
    desc: Start node api
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} npm run dev
