# 🚨 This is currently unused (for example purposes)
# The env var is defined directly in the deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator-config
  namespace: kubernetes-fullstack-api-app
data:
  API_URL: http://api-node.kubernetes-fullstack-api-app.svc.cluster.local:3000
  # API_URL: http://api-golang.kubernetes-fullstack-api-app.svc.cluster.local:8080
  DELAY_MS: "100"
