# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-node-database-url
  namespace: kubernetes-fullstack-api-app
stringData:
  DATABASE_URL: postgres://postgres:password@postgres-postgresql.postgres.svc.cluster.local:5432/postgres
